### PR TITLE
Python 2.7 types

### PR DESCRIPTION
**Pull request by SamuelMarks**
Many IDEs—e.g.: [JetBrains](https://www.jetbrains.com/help/pycharm/type-hinting-in-product.html)—supports type annotation (with code-completion) for Python 2.7.

Not much is required to get this working with your code-generator. I've started, and expect to finish in my next coding session. Opening this up as an RFC for my WiP.

### CODE REVIEW

**Comment by schani** [comment]
@SamuelMarks That's fantastic!

Will the generated code work with the `python2.7` interpreter out of the box?

**Comment by SamuelMarks** [comment]
WiP, but yes.

Hey so what are your thoughts on docstrings?

**Comment by schani** [comment]
@SamuelMarks That's a very unspecific question.  But we produce docstrings in Python, if that's what you're asking.

**Comment by schani** [comment]
We get this error when running the tests:

```
quicktype.py:11: error: Module 'typing' has no attribute 'list'
  |  
  |  
  | Fixture threw an exception
  | {
  | "error": {
  | "command": "mypy quicktype.py",
  | "code": 1
  | },
  | "sample": {
  | "path": "test/inputs/json/priority/combinations.json",
  | "additionalRendererOptions": {
  | "python-version": "2.7"
  | },
  | "saveOutput": false
  | },
  | "cwd": "/app/test/runs/python-199585"
  | }
  | [object Object]
  | at /app/test/test.ts:68:17
  | at step (/app/test/test.ts:32:23)
  | at Object.throw (/app/test/test.ts:13:53)
  | at rejected (/app/test/test.ts:5:65)
  | at <anonymous>
  | at process._tickDomainCallback (internal/process/next_tick.js:228:7)
```

You can run the tests yourself with

```
FIXTURE=python npm test
```

**Comment by SamuelMarks** [comment]
@schani Merged the latest master back into my branch

File: src/quicktype-core/language/Python.ts [hunk 1]
```diff
@@ -1158,12 +1184,12 @@ export class JSONPythonRenderer extends PythonRenderer {
         this.ensureBlankLine();
 
         this.emitBlock(["def to_dict(self)", this.typeHint(" -> dict"), ":"], () => {
-            this.emitLine("result", this.typeHint(": dict"), " = {}");
+            this.emitLine("return {");
             this.forEachClassProperty(t, "none", (name, jsonName, cp) => {
                 const property = { value: ["self.", name] };
-                this.emitLine("result[", this.string(jsonName), "] = ", makeValue(this.serializer(property, cp.type)));
+                this.emitLine("    ", this.string(jsonName), ": ", makeValue(this.serializer(property, cp.type)), ",");
```
Comment (schani) [inline src/quicktype-core/language/Python.ts]: Use `this.indent` for indentation.

File: src/quicktype-core/language/Python.ts [hunk 2]
```diff
@@ -274,9 +274,9 @@ export class PythonRenderer extends ConvenienceRenderer {
 
     protected emitDescriptionBlock(lines: string[]): void {
         if (lines.length === 1) {
-            this.emitLine('"""', lines[0], '"""');
+            this.emitLine("\"\"\"", lines[0], "\"\"\"");
```
Comment (schani) [inline src/quicktype-core/language/Python.ts]: Please remove these from the PR.  We use "prettier" for formatting, and it'll will format it back to the original next time we edit the file.

File: src/quicktype-core/language/Python.ts [hunk 3]
```diff
@@ -579,6 +587,24 @@ function makeValue(vol: ValueOrLambda): Sourcelike {
     return vol.value;
 }
 
+function threeToTwo(input: Sourcelike): Sourcelike {
```
Comment (schani) [inline src/quicktype-core/language/Python.ts]: This seems a weird way of doing things.  What does this function do?  Why don't we generate the `input` in the right way in the first place?  You're basically building a post-processor for quicktype output within quicktype.

File: src/quicktype-core/language/Python.ts [hunk 4]
```diff
@@ -579,6 +587,24 @@ function makeValue(vol: ValueOrLambda): Sourcelike {
...
+    const [loose, types] = (input as any[]).reduce(([p, f], e) => {
+        if (e.length > 1 && e[1] instanceof Array && e[1][0] !== ":" || typeof e === "string" && e[0] === ":")
+            e = e[0];
+        if (e instanceof Array && (e[0].indexOf("->") > -1 || e[0] === ": ") || typeof e === "string" && e.indexOf("->") > -1)
+            return [p, [...f, e]];
+
+        return [[...p, e], f];
+    }, [[], []]);
+
+    if(types.length === -1) console.error(types); // To silent the TypeScript errors ____>
```
Comment (schani) [inline src/quicktype-core/language/Python.ts]: What is the error this is silencing?

Comment (SamuelMarks) [reply src/quicktype-core/language/Python.ts]:
```
src/quicktype-core/language/Python.ts(236,19): error TS6133: 'types' is declared but its value is never read.
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! quicktype@15.0.0 build: `script/build.ts`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the quicktype@15.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     ~/.npm/_logs/2018-08-11T07_12_09_121Z-debug.log
./dist/cli/index.js: line 1: use strict: command not found
./dist/cli/index.js: line 2: syntax error near unexpected token `('
./dist/cli/index.js: line 2: `var __awaiter = (this && this.__awaiter) || function (thisArg, _arguments, P, generator) {'
```

But I'll just add a `@ts-ignore`.

File: src/quicktype-core/language/Python.ts (hunk 3 above)
Comment (SamuelMarks) [reply src/quicktype-core/language/Python.ts]: @schani I feel like the current code is written at the wrong level of abstraction to allow that. You'd really want to work at the Decorated Abstract Syntax Tree level, with the emit/codegen step doing the Python version-specific grammar formation.

Here, I was looking more at what's the fewest lines of code to edit in order to facilitate Python 2.7.

29 lines isn't bad 🖌

File: src/quicktype-core/language/Python.ts [hunk 5]
```diff
@@ -232,6 +232,24 @@ function snakeNameStyle(version: PythonVersion, original: string, uppercase: boo
     );
 }
 
+function threeToTwo(input: Sourcelike): Sourcelike {
+    // @ts-ignore
+    const [loose, types] = (input as any[]).reduce(([p, f], e) => {
```
Comment (schani) [inline src/quicktype-core/language/Python.ts]: You can either do `[loose, _types]` or `[loose, ]` and you won't need the `@ts-ignore`.

File: src/quicktype-core/language/Python.ts (hunk 3 above)
Comment (schani) [reply src/quicktype-core/language/Python.ts]: We don't build syntax trees for output languages.  Look at `withTypeHint` for a start on where to emit the correct code in the first place.

**Comment by schani** [comment]
```
--
  | Traceback (most recent call last):
  | File "main.py", line 1, in <module>
  | import quicktype
  | File "/app/test/runs/python-47002a/quicktype.py", line 11, in <module>
  | from typing import Any, Optional, List, Union, Dict, TypeVar, Callable, Type, cast
  | ImportError: No module named typing
  |  
  | Command failed
  | {
  | "command": "./run.sh main.py \"/app/test/inputs/json/priority/combinations.json\"",
  | "code": 1,
  | "cwd": "/app/test/runs/python-47002a"
  | }
  | Could not run command for JSON output
  | {
  | "error": {
  | "command": "./run.sh main.py \"/app/test/inputs/json/priority/combinations.json\"",
  | "code": 1,
  | "cwd": "/app/test/runs/python-47002a"
  | },
  | "cwd": "/app/test/runs/python-47002a"
  | }
  | Fixture threw an exception
  | {
  | "error": {
  | "error": {
  | "command": "./run.sh main.py \"/app/test/inputs/json/priority/combinations.json\"",
  | "code": 1,
  | "cwd": "/app/test/runs/python-47002a"
  | },
  | "cwd": "/app/test/runs/python-47002a"
  | },
  | "sample": {
  | "path": "test/inputs/json/priority/combinations.json",
  | "additionalRendererOptions": {
  | "python-version": "2.7"
  | },
  | "saveOutput": false
  | },
  | "cwd": "/app/test/runs/python-47002a"
  | }
  | [object Object]
  | at /app/test/test.ts:68:17
  | at step (/app/test/test.ts:32:23)
  | at Object.throw (/app/test/test.ts:13:53)
  | at rejected (/app/test/test.ts:5:65)
  | at <anonymous>
  | at process._tickDomainCallback (internal/process/next_tick.js:228:7)
  | npm ERR! Test failed.  See above for more details.
```

**Comment by SamuelMarks** [comment]
>To run your program, you must have the `typing` module in your Python 2 module search path. Use `pip install typing` to install the module. This also works for Python 3 versions prior to 3.5 that don’t include `typing` in the standard library.
https://mypy.readthedocs.io/en/latest/python2.html#type-checking-python-2-code

File: src/quicktype-core/language/Python.ts (hunk 5 above)
Comment (SamuelMarks) [reply src/quicktype-core/language/Python.ts]: First alternative gave same error, second alternative worked. Done.

File: src/quicktype-core/language/Python.ts (hunk 3 above)
Comment (SamuelMarks) [reply src/quicktype-core/language/Python.ts]: I understand that you don't currently, my opinion is that if you did it would simplify the Python 2/3 emission.

Anyway, from my knowledge of the comparison, all you need to do is convert the Python 3.7 type into a [mypy] type string, and you're good to go. That's what I've done, with a TODO to do the same for function signatures.

**Comment by schani** [comment]
If there's a requirement then this should probably be a separate Python "version".  i.e. we'd have "Python 2.7" and "Python 2.7 with typing".

File: src/quicktype-core/language/Python.ts (hunk 3 above)
Comment (schani) [reply src/quicktype-core/language/Python.ts]: `threeToTwo()` is only used for function/method definitions, right?  Why not instead have a method that takes the name, argument names, their types, and the return type, and emits the function definition line - with type annotations if the options require them - and an optional type annotation comment line if Python 2.7 with typing is selected?  Call it `emitFunction` or `emitDef`, and it takes a function that emits its body, like `emitBlock`.

Comment (SamuelMarks) [reply src/quicktype-core/language/Python.ts]: What I meant was that:

```python
def hello() -> None:
    print 'hello'
```

Becomes:
```python
def hello(): # type: () -> None
    print 'hello'
```

So the type annotation isn't actually changing, just `# type:` is appended and the type annotation is moved outside the code and [appended] into the comment.

Clearly this means it's not a different typing, it's just appending what is already there as a comment.

Comment (schani) [reply src/quicktype-core/language/Python.ts]: I understand.  I don't want code that emits Python 3 and then other code that rewrites it to Python 2.  That is brittle (prone to breakage) and obscures what's going on.  Instead, have an `emitDef` which emits either one, or the other, depending on which option is selected.

**Comment by schani** [comment]
@SamuelMarks What's the status on this?

**Comment by schani** [comment]
Closing due to inactivity.
