### ISSUE TITLE
quicktype fails with 'Cannot find module wordwrap' when pnpm hoisting is disabled

### ISSUE THREAD

**Issue by baraknaveh** [quicktype/quicktype#2863]
`quicktype@23.2.6` uses `wordwrap` at runtime ([`src/cli/index.ts`](https://github.com/quicktype/quicktype/blob/392abdeaef7f7ac556d2d673f6b0a617eb30e9ff/src/cli/index.ts#L49)) but does not declare it as a dependency in `package.json`. It resolves only because `quicktype-core` declares `wordwrap` as a dependency, and in flat `node_modules` layouts (npm, yarn) it gets hoisted to where `quicktype` can find it by accident.

When pnpm's hoisting is disabled (`hoist: false`), this breaks at runtime:

```
Error: Cannot find module 'wordwrap'
Require stack:
- .../node_modules/.pnpm/quicktype@23.2.6_.../node_modules/quicktype/dist/index.js
```

This was originally reported and fixed in #1041, but regressed in #2108 which removed `wordwrap` from `quicktype`'s direct dependencies. #2480 is likely the same issue.

**Workaround** — add a `packageExtensions` entry in `pnpm-workspace.yaml`:

```yaml
packageExtensions:
  "quicktype@23":
    dependencies:
      wordwrap: "*"
```

**Fix** — add `wordwrap` back to `dependencies` in `packages/quicktype/package.json` (it was removed in #2108).

**Comment by schani** [comment]
Confirmed reproducible on current master (v23.3.0, commit `68ecb284`) — this is a triage finding from a systematic sweep of the issue backlog (assisted by Claude); root cause verified locally.

**Root cause:** the CLI imports `wordwrap` at runtime (`src/index.ts:20`, compiled to `dist/index.js:54`), but the root `package.json` only lists `@types/wordwrap` as a devDependency — the real `wordwrap` package is never declared as a direct dependency of `quicktype`. It currently resolves only because it gets hoisted from `quicktype-core`'s own dependency tree. Under npm/yarn/default pnpm this hoisting masks the problem, but with `pnpm` + `hoist=false` (a supported, non-default but standard configuration) node can't resolve it and the CLI crashes on startup. This is a regression of a bug originally fixed in #1041, reintroduced by #2108.

**Assessment:**
- Severity: medium — total CLI crash, but only under strict/non-hoisted installs (pnpm with `hoist=false`), not the common case.
- Fix difficulty: easy — add `"wordwrap": "^1.0.0"` to `dependencies` in the root `package.json` (one line).

**Reproduction:**
```bash
mkdir repro && cd repro
printf 'hoist=false\n' > .npmrc
printf '{"name":"repro","private":true}\n' > package.json
npx --yes pnpm@9 add quicktype@23.3.14
echo '{"name":"x","age":1}' > sample.json
./node_modules/.bin/quicktype --lang typescript sample.json
```
Result:
```
Error: Cannot find module 'wordwrap'
Require stack:
- node_modules/.pnpm/quicktype@23.3.14/node_modules/quicktype/dist/index.js
```

**Comment by schani** [comment]
Retested on current master (662ad5b6). `wordwrap` is now declared as a direct dependency of the root `quicktype` package (`package.json` line 53, `"wordwrap": "^1.0.0"`), and `dist/index.js` requires it directly, so it no longer relies on hoisting from `quicktype-core`. Under pnpm with `hoist=false` this now resolves correctly instead of throwing `Cannot find module 'wordwrap'`. This fix will be in the next release. If you can still reproduce the crash on a current build (e.g. after the next npm publish), please reopen with the repro steps and we'll take another look.

**Comment by baraknaveh** [comment]
Thanks for fixing!
