### ISSUE TITLE
[BUG]: TypeScript input rejects Date (and Map) even though quicktype's own TypeScript output uses Date

### ISSUE THREAD

**Issue by schani** [quicktype/quicktype#2935]
## Issue Type

Input parsing (TypeScript input).

## Context (Environment, Version, Language)

Input Format: TypeScript
Output Language: any (tested with Go)

CLI, npm, or app.quicktype.io: CLI (npm)
Version: 25.0.0-pre1 (also reproduces on 24.0.2)

## Description

Using built-in types in a TypeScript input file fails. For `Date`:

```ts
// input.ts
export interface User {
    id: number;
    createdAt: Date;
}
```

```
$ quicktype --src-lang typescript input.ts -l go
Error: TypeScript error: Cannot find name 'Date'. Do you need to change your target library? Try changing the 'lib' compiler option to 'es2015' or later..
```

`Map<string, boolean>` fails the same way — that case is already reported in #1858; filing this one because `Date` makes the asymmetry stark: quicktype's own generated TypeScript declares properties as `Date` (with `Convert` doing the string↔Date transformation), so round-tripping quicktype's TS output back through `--src-lang typescript` fails on code quicktype itself produced.

The error message is also misleading for CLI users: there is no `lib` compiler option to change — the embedded compiler configuration in the typescript-input package would need to include the standard library types.

## Expected Behavior

- `Date` in TS input maps to the date-time type (mirroring how JSON input infers date-times and TS output renders them as `Date`).
- `Map<K, V>` maps to a map type (#1858), or at minimum both produce a friendly "not supported in TypeScript input, use X instead" message rather than a raw compiler error suggesting an inapplicable fix.

🤖 Filed with [Claude Code](https://claude.com/claude-code)
